site_name: Copilot Studio Agent Academy
site_url: https://microsoft.github.io/agent-academy/
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.tabs.link
    - toc.follow
    - content.code.copy
n
nav:
  - Home: index.md
  - Copilot 099:
      - Welcome: Copilot099/index.md
      - Course Setup: Copilot099/00-course-setup/index.md
      - Introduction to Agents: Copilot099/01-introduction-to-agents/index.md
      - Copilot Studio Fundamentals: Copilot099/02-copilot-studio-fundamentals/index.md
      - Create Declarative Agent: Copilot099/03-create-a-declarative-agent/index.md
      - Create a Solution: Copilot099/04-creating-a-solution/index.md
      - Use Prebuilt Agents: Copilot099/05-using-prebuilt-agents/index.md
      - Create Agent from Conversation: Copilot099/06-create-agent-from-conversation/index.md
      - Add New Topic with Trigger: Copilot099/07-add-new-topic-with-trigger/index.md
      - Add Adaptive Card: Copilot099/08-add-adaptive-card/index.md
      - Add Agent Flow: Copilot099/09-add-an-agent-flow/index.md
      - Add Event Triggers: Copilot099/10-add-event-triggers/index.md
      - Publish Your Agent: Copilot099/11-publish-your-agent/index.md
      - Understanding Licensing: Copilot099/12-understanding-licensing/index.md
      - Secure Your Badge: Copilot099/course-completion-badges/index.md
  - Copilot 101 (Coming Soon): Copilot101/index.md
  - Copilot 201 (Coming Soon): Copilot201/index.md
  - Copilot 301 (Coming Soon): Copilot301/index.md
  - Copilot 401 (Coming Soon): Copilot401/index.md

repo_url: https://github.com/microsoft/agent-academy
repo_name: microsoft/agent-academy
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/includes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2
